
//! Autogenerated weights for pallet_summary
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-16-102`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_summary
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// summary_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_summary.
pub trait WeightInfo {
	fn set_periods() -> Weight;
	fn record_summary_calculation(v: u32, r: u32, ) -> Weight;
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight;
	fn approve_root_without_end_voting(v: u32, ) -> Weight;
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight;
	fn reject_root_without_end_voting(v: u32, ) -> Weight;
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight;
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight;
	fn advance_slot_with_offence(v: u32, ) -> Weight;
	fn advance_slot_without_offence(v: u32, ) -> Weight;
	fn add_challenge(v: u32, ) -> Weight;
	fn set_external_validation_threshold() -> Weight;
	fn set_schedule_period() -> Weight;
	fn set_voting_period() -> Weight;
	fn admin_resolve_challenge() -> Weight;
}

/// Weights for pallet_summary using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn set_schedule_period() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn set_voting_period() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn admin_resolve_challenge() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn set_external_validation_threshold() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:0 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 15_520_000 picoseconds.
		Weight::from_parts(15_945_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::TotalIngresses` (r:1 w:1)
	/// Proof: `Summary::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `r` is `[1, 2]`.
	fn record_summary_calculation(v: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `363 + r * (33 ±0) + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 48_581_000 picoseconds.
		Weight::from_parts(46_720_849, 19963)
			// Standard Error: 16_219
			.saturating_add(Weight::from_parts(389_410, 0).saturating_mul(v.into()))
			// Standard Error: 79_199
			.saturating_add(Weight::from_parts(726_378, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1067 + o * (32 ±0) + v * (74 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (75 ±0)`
		// Minimum execution time: 146_862_000 picoseconds.
		Weight::from_parts(130_356_427, 19963)
			// Standard Error: 34_738
			.saturating_add(Weight::from_parts(578_208, 0).saturating_mul(v.into()))
			// Standard Error: 169_625
			.saturating_add(Weight::from_parts(14_813_125, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn approve_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 55_697_000 picoseconds.
		Weight::from_parts(56_429_017, 19963)
			// Standard Error: 6_680
			.saturating_add(Weight::from_parts(109_007, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1130 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 163_717_000 picoseconds.
		Weight::from_parts(148_794_681, 19963)
			// Standard Error: 47_134
			.saturating_add(Weight::from_parts(469_118, 0).saturating_mul(v.into()))
			// Standard Error: 109_547
			.saturating_add(Weight::from_parts(13_772_009, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn reject_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `574 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 51_751_000 picoseconds.
		Weight::from_parts(52_098_347, 19963)
			// Standard Error: 7_010
			.saturating_add(Weight::from_parts(160_016, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1153 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 102_184_000 picoseconds.
		Weight::from_parts(91_092_832, 19963)
			// Standard Error: 39_176
			.saturating_add(Weight::from_parts(48_878, 0).saturating_mul(v.into()))
			// Standard Error: 91_053
			.saturating_add(Weight::from_parts(13_549_651, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1153 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 123_251_000 picoseconds.
		Weight::from_parts(113_852_519, 19963)
			// Standard Error: 42_369
			.saturating_add(Weight::from_parts(79_624, 0).saturating_mul(v.into()))
			// Standard Error: 98_473
			.saturating_add(Weight::from_parts(12_182_153, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[5, 10]`.
	fn advance_slot_with_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `847 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 82_705_000 picoseconds.
		Weight::from_parts(83_678_131, 17871)
			// Standard Error: 14_356
			.saturating_add(Weight::from_parts(138_193, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn advance_slot_without_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343 + v * (64 ±0)`
		//  Estimated: `17871`
		// Minimum execution time: 33_311_000 picoseconds.
		Weight::from_parts(34_410_416, 17871)
			// Standard Error: 4_961
			.saturating_add(Weight::from_parts(52_237, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn add_challenge(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `847 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 94_201_000 picoseconds.
		Weight::from_parts(95_227_821, 17871)
			// Standard Error: 9_388
			.saturating_add(Weight::from_parts(186_520, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn set_schedule_period() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn set_voting_period() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn admin_resolve_challenge() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	fn set_external_validation_threshold() -> Weight {
		Weight::from_parts(15_945_000, 1489)
	}
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:0 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 15_520_000 picoseconds.
		Weight::from_parts(15_945_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::TotalIngresses` (r:1 w:1)
	/// Proof: `Summary::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `r` is `[1, 2]`.
	fn record_summary_calculation(v: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `363 + r * (33 ±0) + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 48_581_000 picoseconds.
		Weight::from_parts(46_720_849, 19963)
			// Standard Error: 16_219
			.saturating_add(Weight::from_parts(389_410, 0).saturating_mul(v.into()))
			// Standard Error: 79_199
			.saturating_add(Weight::from_parts(726_378, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1067 + o * (32 ±0) + v * (74 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (75 ±0)`
		// Minimum execution time: 146_862_000 picoseconds.
		Weight::from_parts(130_356_427, 19963)
			// Standard Error: 34_738
			.saturating_add(Weight::from_parts(578_208, 0).saturating_mul(v.into()))
			// Standard Error: 169_625
			.saturating_add(Weight::from_parts(14_813_125, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn approve_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 55_697_000 picoseconds.
		Weight::from_parts(56_429_017, 19963)
			// Standard Error: 6_680
			.saturating_add(Weight::from_parts(109_007, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1130 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 163_717_000 picoseconds.
		Weight::from_parts(148_794_681, 19963)
			// Standard Error: 47_134
			.saturating_add(Weight::from_parts(469_118, 0).saturating_mul(v.into()))
			// Standard Error: 109_547
			.saturating_add(Weight::from_parts(13_772_009, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn reject_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `574 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 51_751_000 picoseconds.
		Weight::from_parts(52_098_347, 19963)
			// Standard Error: 7_010
			.saturating_add(Weight::from_parts(160_016, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1153 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 102_184_000 picoseconds.
		Weight::from_parts(91_092_832, 19963)
			// Standard Error: 39_176
			.saturating_add(Weight::from_parts(48_878, 0).saturating_mul(v.into()))
			// Standard Error: 91_053
			.saturating_add(Weight::from_parts(13_549_651, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1153 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 123_251_000 picoseconds.
		Weight::from_parts(113_852_519, 19963)
			// Standard Error: 42_369
			.saturating_add(Weight::from_parts(79_624, 0).saturating_mul(v.into()))
			// Standard Error: 98_473
			.saturating_add(Weight::from_parts(12_182_153, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[5, 10]`.
	fn advance_slot_with_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `847 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 82_705_000 picoseconds.
		Weight::from_parts(83_678_131, 17871)
			// Standard Error: 14_356
			.saturating_add(Weight::from_parts(138_193, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn advance_slot_without_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343 + v * (64 ±0)`
		//  Estimated: `17871`
		// Minimum execution time: 33_311_000 picoseconds.
		Weight::from_parts(34_410_416, 17871)
			// Standard Error: 4_961
			.saturating_add(Weight::from_parts(52_237, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn add_challenge(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `847 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 94_201_000 picoseconds.
		Weight::from_parts(95_227_821, 17871)
			// Standard Error: 9_388
			.saturating_add(Weight::from_parts(186_520, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
}