
//! Autogenerated weights for pallet_avn_consensus
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-12-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `aventus-GM5IX0A`, CPU: `Intel(R) Core(TM) i9-14900HX`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("local")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/avn-parachain-collator
// benchmark
// pallet
// --chain
// local
// --wasm-execution=compiled
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_avn_consensus
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/avn-consensus/src/default_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_avn_consensus.
pub trait WeightInfo {
	fn submit() -> Weight;
	fn clear_consensus() -> Weight;
}

/// Weights for pallet_avn_consensus using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::KnownFeeds` (r:1 w:1)
	/// Proof: `AvnConsensus::KnownFeeds` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::RoundId` (r:1 w:1)
	/// Proof: `AvnConsensus::RoundId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::Reporters` (r:1 w:1)
	/// Proof: `AvnConsensus::Reporters` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::PayloadByHash` (r:1 w:1)
	/// Proof: `AvnConsensus::PayloadByHash` (`max_values`: None, `max_size`: Some(4150), added: 6625, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::VoteCounts` (r:1 w:1)
	/// Proof: `AvnConsensus::VoteCounts` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::LastSubmissionBlock` (r:0 w:1)
	/// Proof: `AvnConsensus::LastSubmissionBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1218`
		//  Estimated: `17871`
		// Minimum execution time: 27_983_000 picoseconds.
		Weight::from_parts(28_678_000, 17871)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::LastSubmissionBlock` (r:1 w:1)
	/// Proof: `AvnConsensus::LastSubmissionBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::RoundId` (r:1 w:1)
	/// Proof: `AvnConsensus::RoundId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::KnownFeeds` (r:1 w:1)
	/// Proof: `AvnConsensus::KnownFeeds` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	fn clear_consensus() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `17871`
		// Minimum execution time: 13_880_000 picoseconds.
		Weight::from_parts(14_601_000, 17871)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::KnownFeeds` (r:1 w:1)
	/// Proof: `AvnConsensus::KnownFeeds` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::RoundId` (r:1 w:1)
	/// Proof: `AvnConsensus::RoundId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::Reporters` (r:1 w:1)
	/// Proof: `AvnConsensus::Reporters` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::PayloadByHash` (r:1 w:1)
	/// Proof: `AvnConsensus::PayloadByHash` (`max_values`: None, `max_size`: Some(4150), added: 6625, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::VoteCounts` (r:1 w:1)
	/// Proof: `AvnConsensus::VoteCounts` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::LastSubmissionBlock` (r:0 w:1)
	/// Proof: `AvnConsensus::LastSubmissionBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1218`
		//  Estimated: `17871`
		// Minimum execution time: 27_983_000 picoseconds.
		Weight::from_parts(28_678_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::LastSubmissionBlock` (r:1 w:1)
	/// Proof: `AvnConsensus::LastSubmissionBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::RoundId` (r:1 w:1)
	/// Proof: `AvnConsensus::RoundId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AvnConsensus::KnownFeeds` (r:1 w:1)
	/// Proof: `AvnConsensus::KnownFeeds` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	fn clear_consensus() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `17871`
		// Minimum execution time: 13_880_000 picoseconds.
		Weight::from_parts(14_601_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}