
//! Autogenerated weights for pallet_authors_manager 
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-09-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-150-3-97`, CPU: `Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_authors_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// default_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_authors_manager.
pub trait WeightInfo {
	fn add_author() -> Weight;
	fn remove_author(v: u32, ) -> Weight;
}

/// Weights for pallet_authors_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AuthorsManager::AuthorAccountIds` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::EthereumPublicKeys` (r:1 w:1)
	/// Proof: `AuthorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryAuthorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryAuthorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `AuthorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorActions` (r:0 w:1)
	/// Proof: `AuthorsManager::AuthorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	fn add_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `22429`
		// Minimum execution time: 126_780_000 picoseconds.
		Weight::from_parts(128_882_000, 22429)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `AuthorsManager::EthereumPublicKeys` (r:10 w:0)
	/// Proof: `AuthorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `AuthorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorAccountIds` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorActions` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:0)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestQueue` (`max_values`: Some(1), `max_size`: Some(79002), added: 79497, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn remove_author(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `706 + v * (274 ±0)`
		//  Estimated: `80487 + v * (1839 ±15)`
		// Minimum execution time: 141_988_000 picoseconds.
		Weight::from_parts(120_962_070, 80487)
			// Standard Error: 37_889
			.saturating_add(Weight::from_parts(7_568_442, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 1839).saturating_mul(v.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AuthorsManager::AuthorAccountIds` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::EthereumPublicKeys` (r:1 w:1)
	/// Proof: `AuthorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryAuthorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryAuthorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `AuthorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorActions` (r:0 w:1)
	/// Proof: `AuthorsManager::AuthorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	fn add_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `22429`
		// Minimum execution time: 126_780_000 picoseconds.
		Weight::from_parts(128_882_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `AuthorsManager::EthereumPublicKeys` (r:10 w:0)
	/// Proof: `AuthorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `AuthorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorAccountIds` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `AuthorsManager::AuthorActions` (r:1 w:1)
	/// Proof: `AuthorsManager::AuthorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:0)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestQueue` (`max_values`: Some(1), `max_size`: Some(79002), added: 79497, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn remove_author(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `706 + v * (274 ±0)`
		//  Estimated: `80487 + v * (1839 ±15)`
		// Minimum execution time: 141_988_000 picoseconds.
		Weight::from_parts(120_962_070, 80487)
			// Standard Error: 37_889
			.saturating_add(Weight::from_parts(7_568_442, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 1839).saturating_mul(v.into()))
	}
}