// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_parachain_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-08, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-4-12`, CPU: `AMD EPYC 7R32`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_parachain-staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// parachain_staking_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_parachain_staking.
pub trait WeightInfo {
	fn set_total_selected() -> Weight;
	fn set_blocks_per_era() -> Weight;
	fn join_candidates(x: u32, ) -> Weight;
	fn schedule_leave_candidates(x: u32, ) -> Weight;
	fn execute_leave_candidates(x: u32, ) -> Weight;
	fn cancel_leave_candidates(x: u32, ) -> Weight;
	fn go_offline() -> Weight;
	fn go_online() -> Weight;
	fn candidate_bond_extra() -> Weight;
	fn signed_candidate_bond_extra() -> Weight;
	fn schedule_candidate_unbond() -> Weight;
	fn signed_schedule_candidate_unbond() -> Weight;
	fn execute_candidate_unbond() -> Weight;
	fn signed_execute_candidate_unbond() -> Weight;
	fn cancel_candidate_unbond() -> Weight;
	fn nominate(x: u32, y: u32, ) -> Weight;
	fn signed_nominate(x: u32, y: u32, ) -> Weight;
	fn schedule_leave_nominators() -> Weight;
	fn signed_schedule_leave_nominators() -> Weight;
	fn execute_leave_nominators(x: u32, ) -> Weight;
	fn signed_execute_leave_nominators(x: u32, ) -> Weight;
	fn cancel_leave_nominators() -> Weight;
	fn schedule_revoke_nomination() -> Weight;
	fn signed_schedule_revoke_nomination() -> Weight;
	fn bond_extra() -> Weight;
	fn signed_bond_extra() -> Weight;
	fn schedule_nominator_unbond() -> Weight;
	fn signed_schedule_nominator_unbond() -> Weight;
	fn execute_revoke_nomination() -> Weight;
	fn execute_nominator_unbond() -> Weight;
	fn signed_execute_nominator_unbond() -> Weight;
	fn cancel_revoke_nomination() -> Weight;
	fn cancel_nominator_unbond() -> Weight;
	fn era_transition_on_initialize(x: u32, y: u32, ) -> Weight;
	fn pay_one_collator_reward(y: u32, ) -> Weight;
	fn base_on_initialize() -> Weight;
	fn select_top_candidates() -> Weight;
	fn note_author() -> Weight;
	fn set_admin_setting() -> Weight;
}

/// Weights for pallet_parachain_staking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: ParachainStaking TotalSelected (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	fn set_total_selected() -> Weight {
		(20_382_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:1)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	fn set_blocks_per_era() -> Weight {
		(21_171_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: Session NextKeys (r:1 w:0)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: ParachainStaking BottomNominations (r:0 w:1)
	// Storage: ParachainStaking TopNominations (r:0 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn join_candidates(x: u32, ) -> Weight {
		(73_382_000 as Weight)
			// Standard Error: 12_000
			.saturating_add((274_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn schedule_leave_candidates(x: u32, ) -> Weight {
		(46_301_000 as Weight)
			// Standard Error: 11_000
			.saturating_add((202_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: Balances Locks (r:2 w:2)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking BottomNominations (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[2, 350]`.
	fn execute_leave_candidates(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 127_000
			.saturating_add((37_830_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn cancel_leave_candidates(x: u32, ) -> Weight {
		(31_562_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((631_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn go_offline() -> Weight {
		(29_513_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn go_online() -> Weight {
		(28_972_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn candidate_bond_extra() -> Weight {
		(50_264_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn signed_candidate_bond_extra() -> Weight {
		(136_192_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_candidate_unbond() -> Weight {
		(32_723_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_candidate_unbond() -> Weight {
		(116_171_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn execute_candidate_unbond() -> Weight {
		(50_555_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn signed_execute_candidate_unbond() -> Weight {
		(137_013_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	fn cancel_candidate_unbond() -> Weight {
		(20_362_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	/// The range of component `y` is `[2, 300]`.
	fn nominate(x: u32, y: u32, ) -> Weight {
		(100_434_000 as Weight)
			// Standard Error: 10_000
			.saturating_add((143_000 as Weight).saturating_mul(x as Weight))
			// Standard Error: 3_000
			.saturating_add((75_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:3 w:2)
	// Storage: ParachainStaking TopNominations (r:2 w:2)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	/// The range of component `y` is `[2, 300]`.
	fn signed_nominate(x: u32, _y: u32, ) -> Weight {
		(51_970_000 as Weight)
			// Standard Error: 85_000
			.saturating_add((51_628_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((2 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn schedule_leave_nominators() -> Weight {
		(35_411_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn signed_schedule_leave_nominators() -> Weight {
		(120_005_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `x` is `[2, 100]`.
	fn execute_leave_nominators(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 35_000
			.saturating_add((31_843_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `x` is `[2, 100]`.
	fn signed_execute_leave_nominators(x: u32, ) -> Weight {
		(26_623_000 as Weight)
			// Standard Error: 39_000
			.saturating_add((32_743_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_leave_nominators() -> Weight {
		(33_202_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_revoke_nomination() -> Weight {
		(35_303_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_revoke_nomination() -> Weight {
		(120_027_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:0)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn bond_extra() -> Weight {
		(68_604_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn signed_bond_extra() -> Weight {
		(167_640_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(9 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_nominator_unbond() -> Weight {
		(36_722_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_nominator_unbond() -> Weight {
		(125_557_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn execute_revoke_nomination() -> Weight {
		(79_565_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(9 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn execute_nominator_unbond() -> Weight {
		(71_344_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(10 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn signed_execute_nominator_unbond() -> Weight {
		(165_410_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(11 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_revoke_nomination() -> Weight {
		(25_982_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_nominator_unbond() -> Weight {
		(31_192_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:1)
	// Storage: ParachainStaking Points (r:1 w:0)
	// Storage: ParachainStaking Staked (r:1 w:2)
	// Storage: System Account (r:302 w:302)
	// Storage: ParachainStaking LockedEraPayout (r:1 w:1)
	// Storage: ParachainStaking AwardedPts (r:9 w:1)
	// Storage: ParachainStaking GrowthPeriod (r:1 w:0)
	// Storage: ParachainStaking Growth (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:0)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:10 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:10 w:0)
	// Storage: ParachainStaking TopNominations (r:10 w:0)
	// Storage: ParachainStaking Total (r:1 w:0)
	// Storage: ParachainStaking AtStake (r:1 w:11)
	// Storage: ParachainStaking SelectedCandidates (r:0 w:1)
	// Storage: ParachainStaking DelayedPayouts (r:0 w:1)
	/// The range of component `x` is `[8, 20]`.
	/// The range of component `y` is `[0, 30000]`.
	fn era_transition_on_initialize(x: u32, y: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 27_446_000
			.saturating_add((218_962_000 as Weight).saturating_mul(x as Weight))
			// Standard Error: 8_000
			.saturating_add((176_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().reads((11 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes((8 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking DelayedPayouts (r:1 w:0)
	// Storage: ParachainStaking Points (r:1 w:0)
	// Storage: ParachainStaking AwardedPts (r:2 w:1)
	// Storage: ParachainStaking AtStake (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking LockedEraPayout (r:1 w:1)
	/// The range of component `y` is `[0, 300]`.
	fn pay_one_collator_reward(y: u32, ) -> Weight {
		(35_569_000 as Weight)
			// Standard Error: 8_000
			.saturating_add((21_733_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(y as Weight)))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(y as Weight)))
	}
	// Storage: ParachainStaking Era (r:1 w:0)
	fn base_on_initialize() -> Weight {
		(3_370_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
	}
	// Storage: ParachainStaking CandidatePool (r:1 w:0)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:20 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:20 w:0)
	// Storage: ParachainStaking TopNominations (r:20 w:0)
	// Storage: ParachainStaking SelectedCandidates (r:0 w:1)
	// Storage: ParachainStaking AtStake (r:0 w:20)
	fn select_top_candidates() -> Weight {
		(402_370_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(63 as Weight))
			.saturating_add(T::DbWeight::get().writes(21 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking AwardedPts (r:1 w:1)
	// Storage: ParachainStaking Points (r:1 w:1)
	// Storage: System BlockWeight (r:1 w:1)
	fn note_author() -> Weight {
		(14_810_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking Delay (r:0 w:1)
	fn set_admin_setting() -> Weight {
		(16_170_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: ParachainStaking TotalSelected (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	fn set_total_selected() -> Weight {
		(20_382_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:1)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	fn set_blocks_per_era() -> Weight {
		(21_171_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: Session NextKeys (r:1 w:0)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: ParachainStaking BottomNominations (r:0 w:1)
	// Storage: ParachainStaking TopNominations (r:0 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn join_candidates(x: u32, ) -> Weight {
		(73_382_000 as Weight)
			// Standard Error: 12_000
			.saturating_add((274_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(8 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn schedule_leave_candidates(x: u32, ) -> Weight {
		(46_301_000 as Weight)
			// Standard Error: 11_000
			.saturating_add((202_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: Balances Locks (r:2 w:2)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking BottomNominations (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[2, 350]`.
	fn execute_leave_candidates(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 127_000
			.saturating_add((37_830_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	fn cancel_leave_candidates(x: u32, ) -> Weight {
		(31_562_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((631_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn go_offline() -> Weight {
		(29_513_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn go_online() -> Weight {
		(28_972_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn candidate_bond_extra() -> Weight {
		(50_264_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn signed_candidate_bond_extra() -> Weight {
		(136_192_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_candidate_unbond() -> Weight {
		(32_723_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_candidate_unbond() -> Weight {
		(116_171_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn execute_candidate_unbond() -> Weight {
		(50_555_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	fn signed_execute_candidate_unbond() -> Weight {
		(137_013_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	fn cancel_candidate_unbond() -> Weight {
		(20_362_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	/// The range of component `y` is `[2, 300]`.
	fn nominate(x: u32, y: u32, ) -> Weight {
		(100_434_000 as Weight)
			// Standard Error: 10_000
			.saturating_add((143_000 as Weight).saturating_mul(x as Weight))
			// Standard Error: 3_000
			.saturating_add((75_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:3 w:2)
	// Storage: ParachainStaking TopNominations (r:2 w:2)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	/// The range of component `x` is `[3, 100]`.
	/// The range of component `y` is `[2, 300]`.
	fn signed_nominate(x: u32, _y: u32, ) -> Weight {
		(51_970_000 as Weight)
			// Standard Error: 85_000
			.saturating_add((51_628_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((2 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((2 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn schedule_leave_nominators() -> Weight {
		(35_411_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn signed_schedule_leave_nominators() -> Weight {
		(120_005_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `x` is `[2, 100]`.
	fn execute_leave_nominators(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 35_000
			.saturating_add((31_843_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `x` is `[2, 100]`.
	fn signed_execute_leave_nominators(x: u32, ) -> Weight {
		(26_623_000 as Weight)
			// Standard Error: 39_000
			.saturating_add((32_743_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_leave_nominators() -> Weight {
		(33_202_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_revoke_nomination() -> Weight {
		(35_303_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_revoke_nomination() -> Weight {
		(120_027_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:0)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn bond_extra() -> Weight {
		(68_604_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(8 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn signed_bond_extra() -> Weight {
		(167_640_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(9 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn schedule_nominator_unbond() -> Weight {
		(36_722_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking Delay (r:1 w:0)
	fn signed_schedule_nominator_unbond() -> Weight {
		(125_557_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn execute_revoke_nomination() -> Weight {
		(79_565_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(9 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn execute_nominator_unbond() -> Weight {
		(71_344_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(10 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: ParachainStaking ProxyNonces (r:1 w:1)
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	// Storage: ParachainStaking CandidateInfo (r:1 w:1)
	// Storage: ParachainStaking MinTotalNominatorStake (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ParachainStaking TopNominations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	fn signed_execute_nominator_unbond() -> Weight {
		(165_410_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(11 as Weight))
			.saturating_add(RocksDbWeight::get().writes(9 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_revoke_nomination() -> Weight {
		(25_982_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking NominatorState (r:1 w:1)
	// Storage: ParachainStaking NominationScheduledRequests (r:1 w:1)
	fn cancel_nominator_unbond() -> Weight {
		(31_192_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:1)
	// Storage: ParachainStaking Points (r:1 w:0)
	// Storage: ParachainStaking Staked (r:1 w:2)
	// Storage: System Account (r:302 w:302)
	// Storage: ParachainStaking LockedEraPayout (r:1 w:1)
	// Storage: ParachainStaking AwardedPts (r:9 w:1)
	// Storage: ParachainStaking GrowthPeriod (r:1 w:0)
	// Storage: ParachainStaking Growth (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:0)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:10 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:10 w:0)
	// Storage: ParachainStaking TopNominations (r:10 w:0)
	// Storage: ParachainStaking Total (r:1 w:0)
	// Storage: ParachainStaking AtStake (r:1 w:11)
	// Storage: ParachainStaking SelectedCandidates (r:0 w:1)
	// Storage: ParachainStaking DelayedPayouts (r:0 w:1)
	/// The range of component `x` is `[8, 20]`.
	/// The range of component `y` is `[0, 30000]`.
	fn era_transition_on_initialize(x: u32, y: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 27_446_000
			.saturating_add((218_962_000 as Weight).saturating_mul(x as Weight))
			// Standard Error: 8_000
			.saturating_add((176_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().reads((11 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes((8 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: ParachainStaking DelayedPayouts (r:1 w:0)
	// Storage: ParachainStaking Points (r:1 w:0)
	// Storage: ParachainStaking AwardedPts (r:2 w:1)
	// Storage: ParachainStaking AtStake (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking LockedEraPayout (r:1 w:1)
	/// The range of component `y` is `[0, 300]`.
	fn pay_one_collator_reward(y: u32, ) -> Weight {
		(35_569_000 as Weight)
			// Standard Error: 8_000
			.saturating_add((21_733_000 as Weight).saturating_mul(y as Weight))
			.saturating_add(RocksDbWeight::get().reads(8 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(y as Weight)))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(y as Weight)))
	}
	// Storage: ParachainStaking Era (r:1 w:0)
	fn base_on_initialize() -> Weight {
		(3_370_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
	}
	// Storage: ParachainStaking CandidatePool (r:1 w:0)
	// Storage: ParachainStaking TotalSelected (r:1 w:0)
	// Storage: ParachainStaking MinCollatorStake (r:1 w:0)
	// Storage: ParachainStaking CandidateInfo (r:20 w:0)
	// Storage: ParachainStaking NominationScheduledRequests (r:20 w:0)
	// Storage: ParachainStaking TopNominations (r:20 w:0)
	// Storage: ParachainStaking SelectedCandidates (r:0 w:1)
	// Storage: ParachainStaking AtStake (r:0 w:20)
	fn select_top_candidates() -> Weight {
		(402_370_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(63 as Weight))
			.saturating_add(RocksDbWeight::get().writes(21 as Weight))
	}
	// Storage: ParachainStaking Era (r:1 w:0)
	// Storage: ParachainStaking AwardedPts (r:1 w:1)
	// Storage: ParachainStaking Points (r:1 w:1)
	// Storage: System BlockWeight (r:1 w:1)
	fn note_author() -> Weight {
		(14_810_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: ParachainStaking Delay (r:0 w:1)
	fn set_admin_setting() -> Weight {
		(16_170_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}