name: CI cron

on:
  schedule:
    # At 3am on sunday
    - cron: '0 3 * * 0'

jobs:
  test-code:
    uses: ./.github/workflows/cargo-test.yml

  build-code:
    needs: [ test-code ]
    uses: ./.github/workflows/cargo-build.yml
    with:
      upload_artifacts: false
    secrets: inherit

  build-code-ubuntu2404:
    needs: [ test-code ]
    uses: ./.github/workflows/cargo-build.yml
    with:
      runs_on: gh-ubuntu-2404-x64
      upload_artifacts: false
    secrets: inherit

