on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  integration_test:
    name: integration-test
    runs-on: avn-runner
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Aventus-Network-Services/avn-node-parachain
          fetch-depth: '0'
          ssh-key: ${{ secrets.avn_node_parachain_key }}
          ref: main

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-10-18
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Task pre integration test
        env:
          STRING_TO_CHANGE: '\(.*\)\("https://github.com/Aventus-Network-Services/avn-parachain"\)\(.*\)\(branch.*\)\(".*"\)\(.*\)'
        run: |
          if [ $GITHUB_EVENT_NAME = 'pull_request_target' ]
          then
              export BRANCH=$GITHUB_HEAD_REF
              export REPO=${{ github.event.pull_request.head.repo.html_url }}
          elif [ $GITHUB_EVENT_NAME = 'workflow_dispatch' ]
          then
              export BRANCH=$GITHUB_REF_NAME
              export REPO="https://github.com/${{ github.repository }}"
          elif [ $GITHUB_EVENT_NAME = 'push' ]
          then
              export BRANCH=${GITHUB_REF#refs/heads/}
              export REPO="https://github.com/${{ github.repository }}"
          fi
          find . -name *.toml -print0 | xargs -0 sed -i "s@$STRING_TO_CHANGE@\1\"$REPO\"\3\4\"$BRANCH\"\6@"
          echo "Changed following configs:"
          git diff -U0

      - name: Integration test
        run: cargo build